### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by ifox**

### CODE REVIEW

**Comment by ifox** [comment]
Updated Travis CI config but as pointed out in https://github.com/lazychaser/laravel-nestedset/pull/519, it would be great to move forward with GitHub Actions.

**Comment by glennjacobs** [comment]
Worth adding PHP 8.1 also?

**Comment by ifox** [comment]
Yes. No point in adding it to the Travis config which doesn't run anymore, but if #519 moves forward, 8.1 should definitely be added to the tests matrix.

**Comment by glennjacobs** [comment]
GitHub Actions have been added into the v5 branch, but not v6?

I guess this PR should bring them in and update them to include PHP 8.1.

Hopefully then we can get it merged and a new release tagged for L9?

**Comment by glennjacobs** [comment]
Laravel 9.0.0 is now released. Any update on this PR?

**Comment by sawirricardo** [comment]
Any news on this?

**Comment by crlcu** [comment]
I'm also watching this.

**Comment by razisayyed** [comment]
Watching...

**Comment by ifox** [comment]
Updated the PR with the changes merged in v5 to move to GitHub Actions.

@lazychaser any chance this can move this forward soon? Thank you!

**Comment by ifox** [comment]
@lazychaser I added PHP 8.1 to the tests matrix and fixed support for PHPUnit typing updates. I did a test run on our fork as this PR needs approval for its workflow to run, and unfortunately, [tests are failing except on PHP 7.2](https://github.com/area17/laravel-nestedset/runs/5125047517), which is quite strange knowing that the tests are running on your v5 branch. Can you help?

**Comment by eudj1n** [comment]
> @lazychaser I added PHP 8.1 to the tests matrix and fixed support for PHPUnit typing updates. I did a test run on our fork as this PR needs approval for its workflow to run, and unfortunately, [tests are failing except on PHP 7.2](https://github.com/area17/laravel-nestedset/runs/5125047517), which is quite strange knowing that the tests are running on your v5 branch. Can you help?

@ifox Just see warnings in 7.2 tests (PHPUnit 8.5.23), for example:

```The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9.Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageMatches() instead```

Other tests uses PHPUnit 9.5.13, where these annotations was removed and so failed.

**Comment by sawirricardo** [comment]
Any fork version for temporary solution?

**Comment by christoph-kluge** [comment]
~Added and fixed deprecations here: https://github.com/lazychaser/laravel-nestedset/pull/550~

~Works fine on php 8.1. In case someone needs this immediately.~

What a coincidence. @ifox pushed a commit almost at the same time.

**Comment by ifox** [comment]
@eudj1n thanks for looking into it, I fixed it and the tests are running now: https://github.com/area17/laravel-nestedset/actions/runs/1823745005.

To be clear, I'm not the maintainer of this package, I'm only trying to help this project to be able to release Laravel 9 support on https://github.com/area17/twill.

@sawirricardo I guess you can use our fork for now if you really need it.

**Comment by phh** [comment]
+1

**Comment by sawirricardo** [comment]
> @eudj1n thanks for looking into it, I fixed it and the tests are running now: https://github.com/area17/laravel-nestedset/actions/runs/1823745005.
> 
> To be clear, I'm not the maintainer of this package, I'm only trying to help this project to be able to release Laravel 9 support on https://github.com/area17/twill.
> 
> @sawirricardo I guess you can use our fork for now if you really need it.

Ah thanks @ifox . I also made one while commenting that though. May be someone will find this useful temporarily.
```
"repositories":[
       {
             "type":"github",
             "url":"https://github.com/sawirricardo/laravel-nestedset"
     }
],
"required":{
      "kalnoy/nested-set":"^6.0"
}
```

**Comment by lazychaser** [comment]
Thanks, guys. Merged and tagged.

**Pull request merged**
