### PR TITLE
Allow for laravel 5.3

### PR DESCRIPTION
**Pull request by morloderex**
Update composer to allow for laravel 5.3

### CODE REVIEW

**Comment by stayallive** [comment]
Was coming here to do this 👍

 Laravel 5.3 is going to be released today or tomorrow would be nice to be able to have this in.

**Comment by lazychaser** [comment]
see #120

**Comment by stayallive** [comment]
5.3 was just released about an hour ago 💃

**Comment by lazychaser** [comment]
Bumped version

**Pull request closed without merging**
