### PR TITLE
Converts the Node class into a Trait

### PR DESCRIPTION
**Pull request by ddimaria**
Hi, I created a trait branch.  This makes Node a trait, so that it can be used with any existing eloquent model rather than forcing the user to extent Node (causes complications with existing code bases). 

This is a breaking change as I updated some of the methods to use the word node at the end b/c Eloquent already uses the append() method.

Before I made the change to trait, I fixed all the tests (using L 5.2) that were broken.  Confirmed all tests still valid after the change to trait.

Because this is now a trait, I had to change the constants to be static vars, so also updated the name convention to be PSR compatible.  I updated NodeSet to match the new variable names.

Thanks for considering.

### CODE REVIEW

**Comment by ParadoxNL** [comment]
+1

**Comment by pet1330** [comment]
+1

**Comment by lazychaser** [comment]
Available now in `5.0.*@dev`

**Comment by lazychaser** [comment]
I've changed version to `4.1.0@dev`

**Pull request merged**
