### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by agentphoenix**
This PR adds support for today's Laravel 8 release.

A note about this PR: Laravel 8 bumps the PHP requirement to PHP 7.3. I'm not sure how you usually handle those kinds of updates with your versioning, but thought I would specifically call it out here.

### CODE REVIEW

**Comment by sebdesign** [comment]
1) You shouldn't change the `php` version constraint to `>=7.3` in composer.json
2) Please add php 7.4 to .travis.yml

**Comment by maherelgamil** [comment]
please review this pull request.

**Comment by agentphoenix** [comment]
@sebdesign Updated

**Comment by Futskito** [comment]
Bump!

**Pull request merged**
