### PR TITLE
update getRelationCountHash (support laravel 8.17+)

### LINKED ISSUE #479: Not compatible to Laravel v8.17.0
Hi there,

the current version of nestedset is not compatible to Laravel v8.17.0, I get this error message:

```
[2020-12-01 16:38:34] production.ERROR: Declaration of Kalnoy\Nestedset\BaseRelation::getRelationCountHash() should be compatible with Illuminate\Database\Eloquent\Relations\Relation::getRelationCountHash($incrementJoinCount = true) {"userId":1,"exception":"[object] (ErrorException(code: 0): Declaration of Kalnoy\\Nestedset\\BaseRelation::getRelationCountHash() should be compatible with Illuminate\\Database\\Eloquent\\Relations\\Relation::getRelationCountHash($incrementJoinCount = true) at /home/my-user/my-site/vendor/kalnoy/nestedset/src/BaseRelation.php:133)
```

To fix the error, I had to modify vendor/kalnoy/nestedset/src/BaseRelation.php and change this:
```
/**
 * Get a relationship join table hash.
 *
 * @return string
 */
public function getRelationCountHash()
{
    return 'nested_set_'.self::$selfJoinCount++;
}
```

to:

```
/**
 * Get a relationship join table hash.
 *
 * @return string
 */
public function getRelationCountHash($incrementJoinCount = true)
{
    return 'nested_set_'.($incrementJoinCount ? self::$selfJoinCount++ : self::$selfJoinCount);
}
```

### PR DESCRIPTION
**Pull request by urakozz**
Current implementation fails with the latest laravel framework v8.17.0  Closes #479

### CODE REVIEW

**Comment by urakozz** [comment]
@SergeyMiracle in the meantime you can use my repo

```
  "require": {
    ....
    "kalnoy/nestedset": "5.0.3",
    ....
  },
  "repositories": [
    { "name": "kalnoy/nestedset", "type": "vcs", "url": "https://github.com/urakozz/laravel-nestedset" }
  ],
```

**Comment by SergeyMiracle** [comment]
@urakozz great 👍

**Comment by vytsci** [comment]
I need this too. My project is now broken after update. Please merge this simple PR ASAP. Thank you.

**Comment by urakozz** [comment]
@vytsci Check my comment above, I use it on production as a temporary fix 🤣

**Comment by vytsci** [comment]
@urakozz for now Ive used "laravel/framework": "~8.16.0" inside my composer.json. After Ill be notified about this PR being merged Ill change back to "laravel/framework": "^8.0". But thanks for suggestion.

**Comment by urakozz** [comment]
Sure, but I was under impression that on 8.16 I had broken `$request->session()->flash(...` 😆

**Comment by it-can** [comment]
@lazychaser can you merge this and release a new version?

**Comment by Okipa** [comment]
@lazychaser, would be interested as well here !

**Pull request merged**
