### PR TITLE
Added a way to retrieve a list of nodes from tree

### PR DESCRIPTION
**Pull request by dmaksimov**
Is "toList" a good name for the method? Couldn't think of anything else to name it.

### CODE REVIEW

**Comment by lazychaser** [comment]
Not sure. It's not self-descriptive. Maybe `toFlattenedTree`?

**Comment by dmaksimov** [comment]
Ok I renamed it to toFlattenedTree since that's a little more descriptive.

**Comment by lazychaser** [comment]
I'll think about it before final release of 4.1

**Comment by lazychaser** [comment]
Renamed to `toFlatTree`

**Pull request merged**
