### PR TITLE
Fixing root method in Query Builder

### PR DESCRIPTION
**Pull request by danilopinotti**
The method returned the first root it encountered and not the root of the node

### CODE REVIEW

**Comment by lazychaser** [comment]
Shouldn't it be placed into another method like `rootOf`? `Category::rootOf($node)`

**Comment by danilopinotti** [comment]
Category::rootOf($node) looks good, but I still do not think it's ideal when it's necessary to access the root of a model from itself.

Note the following example:
```
$rootCategoryName = $product->category->root()->name
```

```
$rootCategory = \App\Model\Category::rootOf($product->category);
$rootCategoryName = $rootCategory->name;
```

It was because of a situation similar to the one I created this PR

The way it is currently (without the merge of this PR), when the root method of a model is called (which I instinctively tried to do), it fetches all roots and returns the first one from the list. That is, it varied according to the updated_at and did not always return the root of the model.

**Comment by lazychaser** [comment]
`root` method is a query builder method, it shouldn't be aware of underlying model that instantiated a query.

**Comment by danilopinotti** [comment]
You're right. Maybe an accessor or 'getRoot()' method could be created and put in the NodeTrait

**Comment by lazychaser** [comment]
Yes, and it will use `rootOf` method of QueryBuilder

**Pull request closed without merging**
